version: 2.1

variables:
  create_env: &create_env
    run:
      name: Create conda environment
      command: |
        mamba env create -f environment.yaml
        source activate gnomad_db
        python -m ipykernel install --user --name gnomad_db --display-name "gnomad_db"

workflows:
  sample:
    jobs:
      - build-and-test
      - test_pip_install

jobs:
  build-and-test:
    docker:
      - image: condaforge/mambaforge
    steps:
      # 🔑 Force HTTPS instead of SSH for GitHub App projects
      - run:
          name: Force HTTPS GitHub checkout
          command: |
            git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout

      - *create_env

      - run:
          name: Run tests
          command: |
            source activate gnomad_db
            snakemake --cores 1
            python -m pytest test_dir/
            python setup.py install

  test_pip_install:
    docker:
      - image: circleci/python:3.9
    steps:
      # 🔑 Force HTTPS instead of SSH for GitHub App projects
      - run:
          name: Force HTTPS GitHub checkout
          command: |
            git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout

      - run:
          name: Test pip installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            python setup.py install --force
            python -m pytest test_dir/
